### PR TITLE
Use atomic increment in instruction counter.

### PR DESCRIPTION
**Pull request by olonho**

### CODE REVIEW

**Comment by evgenykuzyakov** [comment]
Can you provide a description for the change and what does it affect?

**Comment by olonho** [comment]
RuntimeConfig {
    storage_amount_per_byte: 90900000000000000000,
    transaction_costs: RuntimeFeesConfig {
        action_receipt_creation_config: Fee {
            send_sir: 150281562500,
            send_not_sir: 150281562500,
            execution: 150281562500,
        },
        data_receipt_creation_config: DataReceiptCreationConfig {
            base_cost: Fee {
                send_sir: 1392248085750,
                send_not_sir: 1392248085750,
                execution: 1392248085750,
            },
            cost_per_byte: Fee {
                send_sir: 27160286,
                send_not_sir: 27160286,
                execution: 27160286,
            },
        },
        action_creation_config: ActionCreationConfig {
            create_account_cost: Fee {
                send_sir: 132184937500,
                send_not_sir: 132184937500,
                execution: 132184937500,
            },
            deploy_contract_cost: Fee {
                send_sir: 225251625000,
                send_not_sir: 225251625000,
                execution: 225251625000,
            },
            deploy_contract_cost_per_byte: Fee {
                send_sir: 6847135,
                send_not_sir: 6847135,
                execution: 6847135,
            },
            function_call_cost: Fee {
                send_sir: 2262026125000,
                send_not_sir: 2262026125000,
                execution: 2262026125000,
            },
            function_call_cost_per_byte: Fee {
                send_sir: 2184827,
                send_not_sir: 2184827,
                execution: 2184827,
            },
            transfer_cost: Fee {
                send_sir: 158659062500,
                send_not_sir: 158659062500,
                execution: 158659062500,
            },
            stake_cost: Fee {
                send_sir: 170769562500,
                send_not_sir: 170769562500,
                execution: 170769562500,
            },
            add_key_cost: AccessKeyCreationConfig {
                full_access_cost: Fee {
                    send_sir: 137184437500,
                    send_not_sir: 137184437500,
                    execution: 137184437500,
                },
                function_call_cost: Fee {
                    send_sir: 137897687500,
                    send_not_sir: 137897687500,
                    execution: 137897687500,
                },
                function_call_cost_per_byte: Fee {
                    send_sir: 22419443750,
                    send_not_sir: 22419443750,
                    execution: 22419443750,
                },
            },
            delete_key_cost: Fee {
                send_sir: 123024000000,
                send_not_sir: 123024000000,
                execution: 123024000000,
            },
            delete_account_cost: Fee {
                send_sir: 205117687500,
                send_not_sir: 205117687500,
                execution: 205117687500,
            },
        },
        storage_usage_config: StorageUsageConfig {
            num_bytes_account: 100,
            num_extra_bytes_record: 40,
        },
        burnt_gas_reward: Ratio {
            numer: 3,
            denom: 10,
        },
        pessimistic_gas_price_inflation_ratio: Ratio {
            numer: 103,
            denom: 100,
        },
    },
    wasm_config: VMConfig {
        ext_costs: ExtCostsConfig {
            base: 88251848,
            contract_compile_base: 11828582,
            contract_compile_bytes: 74125,
            read_memory_base: 869621600,
            read_memory_byte: 1267359,
            write_memory_base: 934102462,
            write_memory_byte: 908052,
            read_register_base: 838583412,
            read_register_byte: 32856,
            write_register_base: 954900725,
            write_register_byte: 1267440,
            utf8_decoding_base: 1037327262,
            utf8_decoding_byte: 97214363,
            utf16_decoding_base: 1181248200,
            utf16_decoding_byte: 54542463,
            sha256_base: 1513792287,
            sha256_byte: 8039116,
            keccak256_base: 1959076537,
            keccak256_byte: 7169751,
            keccak512_base: 1936247137,
            keccak512_byte: 12216519,
            log_base: 1181248200,
            log_byte: 4399069,
            storage_write_base: 21769859375,
            storage_write_key_byte: 23555471,
            storage_write_value_byte: 17730688,
            storage_write_evicted_byte: 10726325,
            storage_read_base: 19047832125,
            storage_read_key_byte: 10357237,
            storage_read_value_byte: 1900938,
            storage_remove_base: 18296106750,
            storage_remove_key_byte: 12750860,
            storage_remove_ret_value_byte: 3745581,
            storage_has_key_base: 17873339625,
            storage_has_key_byte: 10240986,
            storage_iter_create_prefix_base: 0,
            storage_iter_create_prefix_byte: 0,
            storage_iter_create_range_base: 0,
            storage_iter_create_from_byte: 0,
            storage_iter_create_to_byte: 0,
            storage_iter_next_base: 0,
            storage_iter_next_key_byte: 0,
            storage_iter_next_value_byte: 0,
            touching_trie_node: 5442237750,
            promise_and_base: 488527265,
            promise_and_per_promise: 1835402,
            promise_return: 186681073,
            validator_stake_base: 303944908800,
            validator_total_stake_base: 303944908800,
        },
        grow_mem_cost: 1,
        regular_op_cost: 1147838,
        limit_config: VMLimitConfig {
            max_gas_burnt: 200000000000000,
            max_gas_burnt_view: 200000000000000,
            max_stack_height: 16384,
            initial_memory_pages: 1024,
            max_memory_pages: 2048,
            registers_memory_limit: 1073741824,
            max_register_size: 104857600,
            max_number_registers: 100,
            max_number_logs: 100,
            max_total_log_length: 16384,
            max_total_prepaid_gas: 300000000000000,
            max_actions_per_receipt: 100,
            max_number_bytes_method_names: 2000,
            max_length_method_name: 256,
            max_arguments_length: 4194304,
            max_length_returned_data: 4194304,
            max_contract_size: 4194304,
            max_length_storage_key: 4194304,
            max_length_storage_value: 4194304,
            max_promises_per_function_call_action: 1024,
            max_number_input_data_dependencies: 128,
        },
    },
    account_creation_config: AccountCreationConfig {
        min_allowed_top_level_account_length: 0,
        registrar_account_id: "registrar",
    },
}

**Comment by olonho** [comment]
As QEMU userland emulator runs actual OS threads, it could execute concurrently, and so instruction counter update
must use atomic increment operations, to avoid cost underestimation.
Execution estimation run goes from 120 mins to 175 mins.
New costs computed are above.

**Comment by olonho** [comment]
Cost comparison with current genesis_config.json.
```
./emu-cost/compare_costs.py --safety_second=3 ./genesis.json  ./cost-atomic.txt
```
ext_costs: base: first=264768111 second=264755544 second/first=1.00
ext_costs: contract_compile_base: first=35445963 second=35485746 second/first=1.00
ext_costs: contract_compile_bytes: first=216750 second=222375 second/first=1.03
ext_costs: read_memory_base: first=2609863200 second=2608864800 second/first=1.00
ext_costs: read_memory_byte: first=3801333 second=3802077 second/first=1.00
ext_costs: write_memory_base: first=2803794861 second=2802307386 second/first=1.00
ext_costs: write_memory_byte: first=2723772 second=2724156 second/first=1.00
ext_costs: read_register_base: first=2517165186 second=2515750236 second/first=1.00
ext_costs: read_register_byte: first=98562 second=98568 second/first=1.00
ext_costs: write_register_base: first=2865522486 second=2864702175 second/first=1.00
ext_costs: write_register_byte: first=3801564 second=3802320 second/first=1.00
ext_costs: utf8_decoding_base: first=3111779061 second=3111981786 second/first=1.00
ext_costs: utf8_decoding_byte: first=291580479 second=291643089 second/first=1.00
ext_costs: utf16_decoding_base: first=3543313050 second=3543744600 second/first=1.00
ext_costs: utf16_decoding_byte: first=163577493 second=163627389 second/first=1.00
ext_costs: sha256_base: first=4540970250 second=4541376861 second/first=1.00
ext_costs: sha256_byte: first=24117351 second=24117348 second/first=1.00
ext_costs: keccak256_base: first=5879491275 second=5877229611 second/first=1.00
ext_costs: keccak256_byte: first=21471105 second=21509253 second/first=1.00
ext_costs: keccak512_base: first=5811388236 second=5808741411 second/first=1.00
ext_costs: keccak512_byte: first=36649701 second=36649557 second/first=1.00
ext_costs: log_base: first=3543313050 second=3543744600 second/first=1.00
ext_costs: log_byte: first=13198791 second=13197207 second/first=1.00
ext_costs: storage_write_base: first=64196736000 second=65309578125 second/first=1.02
ext_costs: storage_write_key_byte: first=70482867 second=70666413 second/first=1.00
ext_costs: storage_write_value_byte: first=31018539 second=53192064 second/first=1.71
ext_costs: storage_write_evicted_byte: first=32117307 second=32178975 second/first=1.00
ext_costs: storage_read_base: first=56356845750 second=57143496375 second/first=1.01
ext_costs: storage_read_key_byte: first=30952533 second=31071711 second/first=1.00
ext_costs: storage_read_value_byte: first=5611005 second=5702814 second/first=1.02
ext_costs: storage_remove_base: first=53473030500 second=54888320250 second/first=1.03
ext_costs: storage_remove_key_byte: first=38220384 second=38252580 second/first=1.00
ext_costs: storage_remove_ret_value_byte: first=11531556 second=11236743 second/first=0.97
ext_costs: storage_has_key_base: first=54039896625 second=53620018875 second/first=0.99
ext_costs: storage_has_key_byte: first=30790845 second=30722958 second/first=1.00
ext_costs: storage_iter_create_prefix_base: first=0 second=0 second/first=n/a
ext_costs: storage_iter_create_prefix_byte: first=0 second=0 second/first=n/a
ext_costs: storage_iter_create_range_base: first=0 second=0 second/first=n/a
ext_costs: storage_iter_create_from_byte: first=0 second=0 second/first=n/a
ext_costs: storage_iter_create_to_byte: first=0 second=0 second/first=n/a
ext_costs: storage_iter_next_base: first=0 second=0 second/first=n/a
ext_costs: storage_iter_next_key_byte: first=0 second=0 second/first=n/a
ext_costs: storage_iter_next_value_byte: first=0 second=0 second/first=n/a
ext_costs: touching_trie_node: first=16101955926 second=16326713250 second/first=1.01
ext_costs: promise_and_base: first=1465013400 second=1465581795 second/first=1.00
ext_costs: promise_and_per_promise: first=5452176 second=5506206 second/first=1.01
ext_costs: promise_return: first=560152386 second=560043219 second/first=1.00
ext_costs: validator_stake_base: first=911834726400 second=911834726400 second/first=1.00
ext_costs: validator_total_stake_base: first=911834726400 second=911834726400 second/first=1.00
ext_costs: grow_mem_cost: first=1 second=3 second/first=3.00
^^^ bogus
ext_costs: regular_op_cost: first=3856371 second=3443514 second/first=0.89
```

Same w/o multiplier where it's irrelevant:
```
action_receipt_creation_config: send_sir: first=108059500000 second=150281562500 second/first=1.39
action_receipt_creation_config: send_not_sir: first=108059500000 second=150281562500 second/first=1.39
action_receipt_creation_config: execution: first=108059500000 second=150281562500 second/first=1.39
base_cost: send_sir: first=4697339419375 second=1392248085750 second/first=0.30
base_cost: send_not_sir: first=4697339419375 second=1392248085750 second/first=0.30
base_cost: execution: first=4697339419375 second=1392248085750 second/first=0.30
cost_per_byte: send_sir: first=59357464 second=27160286 second/first=0.46
cost_per_byte: send_not_sir: first=59357464 second=27160286 second/first=0.46
cost_per_byte: execution: first=59357464 second=27160286 second/first=0.46
create_account_cost: send_sir: first=99607375000 second=132184937500 second/first=1.33
create_account_cost: send_not_sir: first=99607375000 second=132184937500 second/first=1.33
create_account_cost: execution: first=99607375000 second=132184937500 second/first=1.33
deploy_contract_cost: send_sir: first=184765750000 second=225251625000 second/first=1.22
deploy_contract_cost: send_not_sir: first=184765750000 second=225251625000 second/first=1.22
deploy_contract_cost: execution: first=184765750000 second=225251625000 second/first=1.22
deploy_contract_cost_per_byte: send_sir: first=6812999 second=6847135 second/first=1.01
deploy_contract_cost_per_byte: send_not_sir: first=6812999 second=6847135 second/first=1.01
deploy_contract_cost_per_byte: execution: first=6812999 second=6847135 second/first=1.01
function_call_cost: send_sir: first=102217625000 second=137897687500 second/first=1.35
function_call_cost: send_not_sir: first=102217625000 second=137897687500 second/first=1.35
function_call_cost: execution: first=102217625000 second=137897687500 second/first=1.35
function_call_cost_per_byte: send_sir: first=1925331 second=22419443750 second/first=11644.46
function_call_cost_per_byte: send_not_sir: first=1925331 second=22419443750 second/first=11644.46
^^^^ Smth fishy going on here? @willemneal @nearmax ideas? Need to investigate.

function_call_cost_per_byte: execution: first=1925331 second=22419443750 second/first=11644.46
transfer_cost: send_sir: first=115123062500 second=158659062500 second/first=1.38
transfer_cost: send_not_sir: first=115123062500 second=158659062500 second/first=1.38
transfer_cost: execution: first=115123062500 second=158659062500 second/first=1.38
stake_cost: send_sir: first=141715687500 second=170769562500 second/first=1.21
stake_cost: send_not_sir: first=141715687500 second=170769562500 second/first=1.21
stake_cost: execution: first=102217625000 second=170769562500 second/first=1.67
full_access_cost: send_sir: first=101765125000 second=137184437500 second/first=1.35
full_access_cost: send_not_sir: first=101765125000 second=137184437500 second/first=1.35
full_access_cost: execution: first=101765125000 second=137184437500 second/first=1.35
delete_key_cost: send_sir: first=94946625000 second=123024000000 second/first=1.30
delete_key_cost: send_not_sir: first=94946625000 second=123024000000 second/first=1.30
delete_key_cost: execution: first=94946625000 second=123024000000 second/first=1.30
delete_account_cost: send_sir: first=147489000000 second=205117687500 second/first=1.39
delete_account_cost: send_not_sir: first=147489000000 second=205117687500 second/first=1.39
delete_account_cost: execution: first=147489000000 second=205117687500 second/first=1.39
storage_usage_config: num_bytes_account: first=100 second=100 second/first=1.00
storage_usage_config: num_extra_bytes_record: first=40 second=40 second/first=1.00
```

**Comment by willemneal** [comment]
> Execution estimation run goes from 120 mins to 175 mins.

Could there be a way to run this in a cloud docker service to decrease this time?

**Comment by ailisp** [comment]
> Could there be a way to run this in a cloud docker service to decrease this time?

You can create a expensive azure instance since we have credits there.

**Comment by ailisp** [comment]
why there was two function_call_cost_per_byte?
```
function_call_cost_per_byte: Fee {
send_sir: 2184827,
send_not_sir: 2184827,
execution: 2184827,
},

...

function_call_cost_per_byte: Fee {
send_sir: 22419443750,
send_not_sir: 22419443750,
execution: 22419443750,
},
```

the first one is close to 1925331

**Comment by ailisp** [comment]
Hmm i misread, function_call_cost_per_byte is correct but add_key_cost.function_call_cost_per_byte it's still problematic, 10000x different, will bin search which cause that wrong

**Pull request merged**
