### PR TITLE
Test that hangs despite panics

### PR DESCRIPTION
**Pull request by nearmax**
To reproduce run test `test_4_10_multiple_nodes` from `test_alphanet_highload.rs`. Observe that panics are getting printed but the test does not shutdown. Observe that `set_hook` is commented out.

### CODE REVIEW

**Comment by mikhailOK** [comment]
Interesting, it actually terminates but takes a really long time.

And replacing shutdown_now with panic hangs for a long time as well:
```        let thread = thread::spawn(|| {
            runtime.spawn(future);
            let _ignored = runtime.block_on(shutdown_rx.map_err(drop).into_future());
            panic!("hehehe panic");
        });
```

**Comment by nearmax** [comment]
Yes, weird :( This thing becomes a blocker, I am currently trying to write some highload tests for benchmarking, profiling, and regression tests, but the code is not terminating. I suggest we go with the approach that I suggested where we replace `tokio::spawn(task)` in major loops like this one: https://github.com/nearprotocol/nearcore/blob/aa76829f349e5309f0ea3a703c2624cccd7bd199/node/coroutines/src/client_task.rs#L813 with `tokio::spawn(task.select(shutdown_rx))`. I am fairly certain it is going to work. Do you have capacity to do it tomorrow? If not then I can do it. We would have to wrap `tokio::spawn(task.select(shutdown_rx))` into `tokio_spawn_shutdownable(task)` which takes `shutdown` from a static variable behind the lock so that we do have to pipe it throughout the codebase. However, with tests that spawn multiple nodes in separate threads they would all automatically reuse the same shutdown channel, which is fine.

**Comment by mikhailOK** [comment]
Found the reason:
-there is a ton of transactions
-One prepare_payload_gossip takes over 100ms, but returns empty so does not tokio::spawn
-One ClientTask::poll call does prepare_payload_gossip in an infinite loop with an interval of 50 ms, Interval lives outside of tokio and does not get shut down
-Active infinite loop, Client never gives control to tokio

There is no way for tokio to stop this madness

**Comment by mikhailOK** [comment]
`tokio::spawn(task.select(shutdown_rx))` will not change anything, the solution is to remove the loop of ClientTask::poll() or at least not let it run infinitely.

**Comment by nearmax** [comment]
I see, good find. So `prepare_payload_gossip` takes >100ms because there are many transactions? Why would it then return empty?

**Comment by nearmax** [comment]
> tokio::spawn(task.select(shutdown_rx)) will not change anything, the solution is to remove the loop of ClientTask::poll() or at least not let it run infinitely.

This will be hard. The internal loop is a reflection of a larger design restriction of the tokio -- poll should only return Async::NotReady if some of the underlying futures that it called returned Async::NotReady. If all futures constantly produce some results there is no way to give away control back to tokio.

**Comment by mikhailOK** [comment]
Poll can return `Ready(())`

**Comment by nearmax** [comment]
> Poll can return `Ready(())`

That will not return control to tokio. Tokio does not know that it is polling a stream, it think it polls a future:
```
 tokio::spawn(self.for_each(|_| Ok(())));
```
The only time the control is returned to tokio is when this future (`self.for_each(|_| Ok(()))`) returns `NotReady`, which only happens when that `poll` returns `NotReady`.

**Pull request closed without merging**
