### PR TITLE
fix: disable epoch info gc for now

### PR DESCRIPTION
**Pull request by bowenwang1996**
Currently we would garbage epoch information right after the epoch switch, which causes many problems including rpc not able to fetch chunks/blocks in the past epoch, not able to verify blocks in the past epoch, etc. I think it is safer to disable it for now and maybe consider implementing it properly when we redo the syncing code.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
@Kouprin can you help fix the store validator code?

**Comment by Kouprin** [comment]
@bowenwang1996 please check if could we enable `block_epoch_exists` in Store Validator. The following steps may help:

1. Uncomment `block_epoch_exists` check.
2. Run custom Nightly.
3. See all fails happened because of `block_epoch_exists`.
4. Decide could we fix failures if any appear.
5. Fix failures and enable `block_epoch_exists` _OR_ describe why we cannot do that in comments for `block_epoch_exists`

**Comment by bowenwang1996** [comment]
@Kouprin I don't see why we cannot enable it. Do you want to do it in another PR or in this one?

**Comment by Kouprin** [comment]
> @Kouprin I don't see why we cannot enable it. Do you want to do it in another PR or in this one?

I have no preferences. It might be better to have a separate PR as for another purpose but it's up to you.

**Comment by bowenwang1996** [comment]
@SkidanovAlex no Cargo.lock change after merging with master :)

**Pull request merged**
