### PR TITLE
feat(thread): Run PeerManager in separate thread.

### PR DESCRIPTION
**Pull request by mfornet**
Spawn PeerManagerActor in its own thread since it can run concurrently with other actor in the system without any problem.

Test Plan
=======
- Check there is no regression

### CODE REVIEW

**Comment by mfornet** [comment]
> How are we sure that there is no regression?

Because of tests? is there anyway to trigger nightly for non-master?  I'm running them now locally with bo script.

**Comment by bowenwang1996** [comment]
@mfornet yes, you can trigger nightly test with https://buildkite.com/nearprotocol/nightly

**Comment by mfornet** [comment]
> @mfornet yes, you can trigger nightly test with https://buildkite.com/nearprotocol/nightly

Already ran on nightly [here](https://buildkite.com/nearprotocol/nightly/builds/56#7cc19b9c-82b6-454a-b5b7-dce5b9d49cd5). Seems to be passing but I see some tests failing in the logs. Some of those tests are not being displayed on http://nightly.neartest.com/ so it is hard to tell whether they start failing now or were already failing before.

**Comment by bowenwang1996** [comment]
@mfornet is the CI issue resolved?

**Comment by mfornet** [comment]
> @mfornet is the CI issue resolved?

@bowenwang1996 I don't thinks so. It seems to be related to #2859 (see [comment](https://github.com/nearprotocol/nearcore/pull/2859#issuecomment-646805020)).

**Pull request merged**
