### PR TITLE
revert Cargo.lock change

### LINKED ISSUE #2761: Pytests do not fail properly
When a pytest is expected to fail due to node crash, I observe the following:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 423, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 331, in _raise_timeout
    self, url, "Read timed out. (read timeout=%s)" % timeout_value
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='127.0.0.1', port=3041): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tests/sanity/state_sync4.py", line 74, in <module>
    status1 = nodes[1].get_status()
  File "lib/cluster.py", line 124, in get_status
    r = requests.get("http://%s:%s/status" % self.rpc_addr(), timeout=5)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=3041): Read timed out. (read timeout=5)
```
and there is no indication of any error in the logs as well. It is not clear to me what happened and makes it very difficult to debug.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Revert the change to Cargo.lock introduced in #2672. The change caused some unexpected behaviors such as #2761.

Fixes #2761.

Test plan
---------
Test in the branch `node-crash-no-log-repro` that before this commit, the pytest `state_sync4.py` will fail with no indication of node crashing whereas after this commit the stack trace is printed in stderr.

### CODE REVIEW

**Comment by mfornet** [comment]
Why is this needed? Isn't Cargo.lock supposed to be generated automatically and deterministically. If you compile on top of this branch, doesn't Cargo.lock change back again?

**Comment by chefsale** [comment]
Hmm, what they say. Libraries shouldn't have Cargo.lock, but binaries are encouraged to have one:

https://stackoverflow.com/questions/43667176/what-files-in-a-cargo-project-should-be-in-my-gitignore

**Comment by chefsale** [comment]
Binaries on the other hand should have a specified set of dependencies for deterministic builds across whatever machine is building the package by ensuring that the exact same dependencies are being compiled. So, in this case I believe we shouldn't really delete this one, rather find why is the behavior changed now and how do we fix it.

**Comment by frol** [comment]
As per my finding, some of the new dependencies case this issue. I was yet to identify which one, but we can go with this solution to make the nightly tests green again.

**Comment by chefsale** [comment]
@frol happy with that, maybe just create an issue for that we can track. :)

**Comment by frol** [comment]
@chefsale #2722 is one

**Pull request merged**
