### PR TITLE
dashboard for different network and a few fix

### PR DESCRIPTION
**Pull request by ailisp**
There are places looks weird. I've fixed most prometheus/grafana query related and ui related ones. The remaining should because of data source. Please try to list issues and other kind of metrics you would like to see here. I'll go back and fix soon.

 Staging testnet dashboard:
http://35.223.230.128:3000/d/staging-testnet/staging-testnet?orgId=1&refresh=5s&kiosk
Main testnet dashboard:
http://35.223.230.128:3000/d/main-testnet/main-testnet?orgId=1&refresh=5s&kiosk
stakewars dashboard:
http://35.223.230.128:3000/d/stakewars-testnet/stakewars-testnet?orgId=1&refresh=5s&kiosk

@frol @ilblackdragon is it a good idea to plug in these dashboard somewhere in explorer

### CODE REVIEW

**Comment by vgrichina** [comment]
@ailisp how is this deployed?

**Comment by ailisp** [comment]
> @ailisp how is this deployed?

on a gcloud instance, one docker prometheus, one docker grafana.

**Comment by vgrichina** [comment]
> > @ailisp how is this deployed?
> 
> on a gcloud instance, one docker prometheus, one docker grafana.

does it have to be there? It's going to be hard to keep up to date without CD. If it's just HTTP service likely can be hosted on Render.

**Comment by ailisp** [comment]
Does not have to be. render looks great, I'm taking a look at it
now. solana uses buildkite to deploy prometheus/grafana, is that something
similar

**Pull request merged**
