### PR TITLE
Fixing expensive tests

### LINKED ISSUE #1156: Expensive tests are broken
Our expensive tests are broken and were not run on CI.
To reproduce:
* Checkout the most recent `master`/`staging` branch;
* Run
```bash
  cargo test --all --features expensive_tests
```

Observe ~30 broken tests.

It seems like expensive tests were not run by the CI pipeline because there were configured to run daily on schedule (oppose to on each branch commit) but now the schedule was removed somehow from the Gitlab dashboard and we were not running them for a while.

### PR DESCRIPTION
**Pull request by nearmax**
Fixes #1156 

- [x] Fixed base58->base64 encoding;
- [x] Fixed issue with signing with wrong public key;
- [x] WIP Sending transaction fails with `RpcError` `"send_tx_commit has timed out."`

### CODE REVIEW

**Comment by nearmax** [comment]
Seems like the nodes just get stuck on block 1.

**Comment by bowenwang1996** [comment]
There appears to be some issue with too many open files when running all the expensive tests together. I think it might be related to actix, but don't have time right now to look deeply into this.

**Comment by nearmax** [comment]
Actix opens files? Maybe it is somehow related to actix opening too many sockets me and @evgenykuzyakov can see on our machines that Actix opens ~64k sockets (based on logs). Socket is a file descriptor so maybe that's confusing. Independently on it, expensive tests are really important, because none of the tests in `near/tests` try submitting transactions.

**Comment by nearmax** [comment]
Btw, expensive tests do not all run together. There is a special macro `heavy_test` that prevents them from starting at the same time using `Mutex` and `ShutdownableThread` makes sure previous tests shuts down before the next one starts.

But also, you can run tests individually and see that they do not pass.

**Comment by bowenwang1996** [comment]
Yes I am aware that `heavy_test` exists. But they still fail when run together for some reason. Which test fail when you run it separately?

**Comment by nearmax** [comment]
> Yes I am aware that `heavy_test` exists. But they still fail when run together for some reason. Which test fail when you run it separately?

I haven not recorded it. Do they all pass for you when run separately?

**Comment by bowenwang1996** [comment]
I didn't run all of them (it would take a while), but from about 10 tests I run, all of them pass. I can run all of them if that's desired. But I think it would be helpful if we can fix this problem of too many open files and do not have to run 40 tests manually.

**Comment by nearmax** [comment]
Okay, now that I pull the most recent commit from this branch I cannot find a test that fails when run individually. However, it would be nice to make it work, because they are otherwise useless. No one is going to run 30 tests by hand, it is equal to not having them.

**Comment by bowenwang1996** [comment]
While trying to fix the expensive tests after merging with staging, I noticed that the ones that involve running nodes have different behavior than the runtime only tests due to storage rent. Since the behaviors diverge, we cannot use the same code for both runtime unit tests and integration tests. So we should consider either separating the tests (breaking the existing test framework) or relax the conditions. @evgenykuzyakov @nearmax

**Comment by ilblackdragon** [comment]
The behavior diverges, because in runtime tests, some tests specify the
Genesis config properties around rent.

We have two options:
- also just specify those options in non runtime tests (e.g copy that
setting we have with expensive storage into the other test)
- move Genesis configuration be some part of standard test cases info, like
a each test specifies which Genesis scenario it needs.

**Comment by ilblackdragon** [comment]
Right now still a bunch of tests with  fail in staging:

cargo test -p nearcore --all-features

failures:
    test::test_access_key_smart_contract_testnet
    test::test_add_access_key_function_call_testnet
    test::test_add_access_key_with_allowance_testnet
    test::test_add_existing_key_testnet
    test::test_add_key_testnet
    test::test_create_account_again_testnet
    test::test_create_account_failure_already_exists_testnet
    test::test_create_account_failure_invalid_name_testnet
    test::test_create_account_testnet
    test::test_delete_access_key_testnet
    test::test_delete_access_key_with_allowance_testnet
    test::test_delete_key_last_testnet
    test::test_delete_key_not_owned_testnet
    test::test_delete_key_testnet
    test::test_nonce_update_when_deploying_contract_testnet
    test::test_redeploy_contract_testnet
    test::test_refund_on_send_money_to_non_existent_account_testnet
    test::test_send_money_testnet
    test::test_smart_contract_bad_method_name_testnet
    test::test_smart_contract_empty_method_name_with_no_tokens_testnet
    test::test_smart_contract_self_call_testnet
    test::test_smart_contract_simple_testnet
    test::test_smart_contract_with_args_testnet

**Comment by nearmax** [comment]
@SkidanovAlex @bowenwang1996 Is this an abandoned PR? Should it be closed?

**Comment by bowenwang1996** [comment]
I think this should still be fixed unless we don't want to run those tests any more.

**Comment by ilblackdragon** [comment]
There might be still some file descriptor leak, but on my laptop with 10k ulimit all `--p nearcore` tests pass. Let's merge this @nearmax @SkidanovAlex to get make nightly greener.

**Comment by nearmax** [comment]
> There might be still some file descriptor leak, but on my laptop with 10k ulimit all `--p nearcore` tests pass. Let's merge this @nearmax @SkidanovAlex to get make nightly greener.

Sure. I cannot approve it since it is on my name. Also, the CI seems to be failing.

**Pull request closed without merging**
