### PR TITLE
fix(runtime): Fix empty method_names bug

### PR DESCRIPTION
**Pull request by evgenykuzyakov**
Fixes: #2183 

# Test plan:
- Extracted the code into utils crate and added unit tests.

### CODE REVIEW

**Comment by evgenykuzyakov** [comment]
@nearmax Do I need to bump `near-runtime-fees` and `near-vm-errors` to 0.4.5?

**Comment by nearmax** [comment]
> @nearmax Do I need to bump `near-runtime-fees` and `near-vm-errors` to 0.4.5?

I would bump on crates in runtime for consistency reason, because it is then easier to track if something got out of date.

**Comment by fckt** [comment]
We have a lot of imports we pass a complex structures to. 

```rust
&mut self,
        promise_idx: u64,
        account_id_len: u64,
        account_id_ptr: u64,
        method_name_len: u64,
        method_name_ptr: u64,
        arguments_len: u64,
        arguments_ptr: u64,
        amount_ptr: u64,
        gas: u64,
```

```rust
pub fn promise_batch_action_function_call(
        &mut self,
        promise_idx: u64,
        method_name_len: u64,
        method_name_ptr: u64,
        arguments_len: u64,
        arguments_ptr: u64,
        amount_ptr: u64,
        gas: Gas,
```

```rust
pub fn promise_then(
        &mut self,
        promise_idx: u64,
        account_id_len: u64,
        account_id_ptr: u64,
        method_name_len: u64,
        method_name_ptr: u64,
        arguments_len: u64,
        arguments_ptr: u64,
        amount_ptr: u64,
        gas: u64,
```

Do anybody was thinking to pass Promises as a Borsh-serialized structures? I would remove a lot of error-prone boilerplate.

**Comment by evgenykuzyakov** [comment]
> Do anybody was thinking to pass Promises as Borsh-serialized structures? I would remove a lot of error-prone boilerplate.

This was done before `borsh` was widely adopted and maybe before Rust was a lang of choice for near contracts. It would also force all languages that we want to support to implement `borsh`, which was not a requirement with manual functions.

**Comment by nearmax** [comment]
> It would also force all languages that we want to support to implement `borsh`, which was not a requirement with manual functions.

@fckt @evgenykuzyakov That was the main reason. By passing arguments as Borsh we a pushing a lot of boilerplate complexity into the contract itself. By having argument reading inside the near-vm-logic we are keeping boilerplate inside the runtime.

Also, for every argument for having arguments as Borsh one can do one step further and argue that we don't even need more than one host function and just encode different functions as variants of a single enum.

**Comment by fckt** [comment]
@evgenykuzyakov @nearmax 

From https://webassembly.org/docs/modules

> A module can declare a sequence of exports which are returned at instantiation time to the host environment. Each export has three fields: a name, which is required to be *valid UTF-8*, whose meaning is defined by the host environment, a type, indicating whether the export is a function, global, memory or table, and an index into the type’s corresponding index space.

What if the is a `,` in the method name?

**Comment by nearmax** [comment]
> @evgenykuzyakov @nearmax
> 
> From https://webassembly.org/docs/modules
> 
> > A module can declare a sequence of exports which are returned at instantiation time to the host environment. Each export has three fields: a name, which is required to be _valid UTF-8_, whose meaning is defined by the host environment, a type, indicating whether the export is a function, global, memory or table, and an index into the type’s corresponding index space.
> 
> What if there is a `,` (comma) in the export name?

Currently, we won't be able to create an access key that calls it.

**Pull request merged**
