### PR TITLE
Turn on deterministic wasmer runtime

### PR DESCRIPTION
**Pull request by ailisp**
Based on https://github.com/wasmerio/wasmer/blob/master/lib/runtime/Cargo.toml and my test this is the feature flag to turn on deterministic execution.

### CODE REVIEW

**Comment by ailisp** [comment]
@nearmax this is ready to review too, last time i was wrong to suppose this was singlepass (actually it's cranelift), with experiment all these feature flags with fuzz tester, the only flag that gives 100% stability:
```
wasmer-runtime-core = { version = "0.12.0" }
wasmer-runtime = { version = "0.12.0", features = ["deterministic-execution"]}
```
Note the default feature is also turned on, which indicates a cranelift backend. cargo build logs also shows:
```
   Compiling cranelift-codegen v0.44.0
```

**Comment by mikhailOK** [comment]
Are we giving up on singlepass backend?
Compiler bombs are still an issue

**Comment by ailisp** [comment]
I thought so too, because wasmer-runtime Cargo.toml:
deterministic-execution = [
"wasmer-singlepass-backend/deterministic-execution",
"wasmer-runtime-core/deterministic-execution"]

But then if i add "singlepass" feature to wasmer-runtime fuzz test gives
98.x% stability
You can check result by comment/uncomment this file:
https://github.com/nearprotocol/deterministic-wasmer/blob/master/Cargo.toml

Since the default feature indicate default backend is "cranelift", and
default feature works well with "deterministic" feature, then
"wasmer-singlepass-backend/deterministic-execution"
looks very confusing.

**Comment by evgenykuzyakov** [comment]
Bump, @ailisp @nearmax . Should we upgrade to 0.14.1 and merge it?

**Comment by nearmax** [comment]
> Bump, @ailisp @nearmax . Should we upgrade to 0.14.1 and merge it?

Let me get a comment from Wasmer.

**Comment by syrusakbary** [comment]
`deterministic-execution` is a feature flag that can be activated regardless of the backend. It mainly affects when validating the Wasm file to disallow certain types/operations.

You should probably activate it, and still use the `backend-singlepass` feature.

```toml
wasmer-runtime = { version = "0.14.1", features = ["default-backend-singlepass"], default-features = false }
wasmer-runtime-core = { version = "0.14.1", features = ["backend-singlepass", "deterministic-execution"]}
```

**Comment by nearmax** [comment]
The way this feature flag works right now is that it will prohibit floats, which we don't want to do. I am closing this PR then.

**Pull request closed without merging**
