### PR TITLE
Bumped neard version to 1.0.0

### PR DESCRIPTION
**Pull request by chefsale**

### CODE REVIEW

**Comment by ilblackdragon** [comment]
Hm, are we planning to bump to 2.0 as soon as https://github.com/nearprotocol/nearcore/issues/2676 lands? Or should we wait with 1.0 until then?

**Comment by chefsale** [comment]
I'm fine with both approaches, maybe just upgrading to 2.0 would be a good thing to retest the whole flow one more time once this lands. As we currently have mainnet already running @bowenwang1996  and I discussed there is not point of waiting and lets not be conservative to bump major if we need. Both options work for me.

**Comment by bowenwang1996** [comment]
@ilblackdragon I see no issue with bumping to 2.0. Is the concern that our current code is not stable enough to be considered "1.0"?

**Comment by chefsale** [comment]
@ilblackdragon can we ship this and release a new 1.0.0 with this diff included or should we land it as a lower version 0.9.0?

**Pull request merged**
