### PR TITLE
fix(storage): ColTrieChanges is indexed by (block_hash, shard_id)

### PR DESCRIPTION
**Pull request by Kouprin**
Fixes https://github.com/nearprotocol/nearcore/issues/2564

### CODE REVIEW

**Comment by damons** [comment]
Setting estimate to 1 as it's mostly done and depends on Misha.

**Comment by damons** [comment]
Adding this to Chain Stability Push Epic.  Please do change it if this is incorrect.

**Comment by bowenwang1996** [comment]
@damons I think chain stability push is created in the context of mainnet (phase 2), so I don't think it is appropriate.

**Comment by ailisp** [comment]
Yeah it's mandatory to bump protocol version now (migration script is empty besides bump protocol version since no change made to genesis file), so deployment will see protocol version changed, and state dump, delete old db, create db in new format

**Comment by frol** [comment]
I don't see the any change in the stored data :thinking:

**Comment by Kouprin** [comment]
> I don't see the any change in the stored data 🤔

@frol 
Before: only Shard 0 data is deleted
After: all Shards data are deleted

it's the same only in case of having single shard

**Comment by bowenwang1996** [comment]
@Kouprin @nearmax looks like we don't need migration in this case since we don't have more than 1 shard on any of the networks.

**Comment by SkidanovAlex** [comment]
> @Kouprin @nearmax looks like we don't need migration in this case since we don't have more than 1 shard on any of the networks.

It appears to requre the migration, because the indexing of one of the collections has changed? All the data in that collections won't be readable after the restart.

**Comment by frol** [comment]
> It appears to requre the migration, because the indexing of one of the collections has changed?

Which one?

**Comment by Kouprin** [comment]
@SkidanovAlex I guess indexing has been changed here: https://github.com/nearprotocol/nearcore/pull/2638 (get_shard_id_and_hash_from_key)

so @frol might be right about noop for indexing at this PR

**Comment by mikhailOK** [comment]
Before:
```
                    .get_ser(ColTrieChanges, block_hash.as_ref())?
```
After:
```
                         .get_ser(ColTrieChanges, &get_block_shard_id(&block_hash, shard_id))?
```
Indexing has changed, version update is needed.

**Comment by frol** [comment]
Indeed! @mikhailOK good catch!

**Comment by Kouprin** [comment]
it seems automerge doesn't work

**Pull request merged**
