### PR TITLE
Avoid panic while panicking because of actix isn't running

### PR DESCRIPTION
**Pull request by ailisp**
Some of our tests don't have actix running. @Kouprin found when assert in such tests failed it's not able to see which test fails, only `thread panicked while panicking`. So check actix is running and only shutdown it if so fix this.

Test Plan
---------
```
#[test] 
fn test_assert() {
init_stop_on_panic();
assert(false);
}
```
should give assert fails instead of `thread panicked while panicking`

### CODE REVIEW

**Comment by ailisp** [comment]
Note: with_current panic if actix not running. it will be better if I can tell actix is running or not, but seems I can't find such a public function.
```
    pub fn with_current<F, R>(f: F) -> R
    where
        F: FnOnce(&System) -> R,
    {
        CURRENT.with(|cell| match *cell.borrow() {
            Some(ref sys) => f(sys),
            None => panic!("System is not running"),
        })
    }
```

**Comment by ailisp** [comment]
> Does this still work when you have actix running?

Yes

**Comment by SkidanovAlex** [comment]
I just had `test panicked while panicking` in one of my runs, cherry-picking this change didn't help.

Commit hash 43ff1c115a75f994e2cc3f1c567ed3df95269942, cherry-pick your change, run `cargo test --all`

**Comment by ailisp** [comment]
@SkidanovAlex Seems my test wasn't run test and catch_unwind doesn't work in panic::set_hook :( Need to find a different fix

**Comment by ailisp** [comment]
Seems go through all current and future test to ensure they're using actix is more work. I made a PR to https://github.com/actix/actix-net/pull/99 so we can know if actix is running without panic

**Comment by Kouprin** [comment]
> Seems go through all current and future test to ensure they're using actix is more work. I made a PR to [actix/actix-net#99](https://github.com/actix/actix-net/pull/99) so we can know if actix is running without panic

This is awesome.

**Comment by ailisp** [comment]
@bowenwang1996 @SkidanovAlex PR in actix is merged, ready for this PR now :)

**Pull request merged**
