### PR TITLE
Add local flag

### PR DESCRIPTION
**Pull request by mfornet**
Expose flag in cli that build "testnet" config with local ports.

### CODE REVIEW

**Comment by mfornet** [comment]
> I am not sure this is needed. CI can overwrite the config to use specific ports.

I'm using it for local debugging.

**Comment by nearmax** [comment]
> > I am not sure this is needed. CI can overwrite the config to use specific ports.
> 
> I'm using it for local debugging.

Why it cannot be done through the config modifications?

**Comment by mfornet** [comment]
> > > I am not sure this is needed. CI can overwrite the config to use specific ports.
> > 
> > 
> > I'm using it for local debugging.
> 
> Why it cannot be done through the config modifications?

Yes, it can be done, I just don't want to do it manually, so the other option is make a script (which actually I already have), but I could drop it in favor of this. Others might need this to run several nodes locally.

**Comment by nearmax** [comment]
I would keep the CLI interface minimal and keep all helpers like this in some scripts.

**Comment by mfornet** [comment]
> I would keep the CLI interface minimal and keep all helpers like this in some scripts.

Fair enough

**Pull request closed without merging**
