### PR TITLE
Change state dump to binary format

### LINKED ISSUE #2070: Fix performance of state dump process
Currently state dump on TestNet can take up to 1 hour for only ~50MB of state:
 * One reason is Json. We should use a binary format.
 * Another reason is usage of TrieIterator. This can be replace it by just iterating over all values in the STATE column and checking if they are Leafs of the Trie.

Note, let's add this directly to `master` as this is required to actually upgrade our live network.

### PR DESCRIPTION
**Pull request by bowenwang1996**
Instead of dumping state in a json file which is slow, this PR changes it to dumping state in a binary format. Fixes #2070.

Test plan
---------
Manually test this with a local node to make sure that the state is preserved correctly after state dumping.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
@nearmax dumping testnet state stored in `testnet.json` takes 2 seconds.

**Comment by mikhailOK** [comment]
@bowenwang1996 dumping one state case did not slow down, the possible regression is from dumping all previous states after this change.
It's also data that will never be garbage collected

**Comment by bowenwang1996** [comment]
@mikhailOK I don't understand what you meant. I ran the tool against an actual node data.

**Comment by bowenwang1996** [comment]
I just tested this with the current testnet state. Dumping it on the testnet node whose cpu isn't powerful at all takes less than 2 minutes so I think it is acceptable.

**Comment by ilblackdragon** [comment]
@bowenwang1996 if you are saying it takes 2 minutes - we fixed the 20 minute delay in starting node / opening rocksdb?

**Comment by nearmax** [comment]
> @bowenwang1996 if you are saying it takes 2 minutes - we fixed the 20 minute delay in starting node / opening rocksdb?

I think what @bowenwang1996 is saying is that it takes 2 minutes to dump the state. He did not say how long it takes to start the node.

**Comment by bowenwang1996** [comment]
The slowness in restarting the node seems to be related to rocksdb compaction. There is a discussion here https://github.com/nearprotocol/nearcore/issues/2105 and @ailisp is working on it.

**Pull request merged**
