### PR TITLE
void

### PR DESCRIPTION
**Pull request by lazaridiscom**
(re #2141)

- tiny typos (CAPITAL on titles)

todo
- basic build instructions should be right within the readme, e.g. "ubuntu", then link to the manual
- manual needs to be updated/restrcutured
- remove emoj (keep core code technical)

### CODE REVIEW

**Comment by nearmax** [comment]
Assigned to @potatodepaulo for triaging as per guidelines.

**Comment by lazaridiscom** [comment]
> 
> 
> Assigned to @potatodepaulo for triaging as per guidelines.

@potatodepaulo says: "Talk to me about taking down the shitty old institutions"

I say: the process-overhead (here, for this trivial PR) actually reminds me "shitty old institutions".

But then: who am I?

**Comment by lazaridiscom** [comment]
> These READMEs need some love but it's low priority.

The overall documentation needs an "outsider-review", and DX/UX is always(!) highest priority (not for core-devs of course, they need to stay in their cores to do their magic).

> Remember, even trivial links need to be checked so we're not accidentally adding phishing attacks to our stuff.

You're right of course, that slipped me...

> You can ping me on email/telegram/discord with what you think the process should to be.

Me more the "issue-centric" type, but thanks for email channel, will possibly use it the next hour.

**Comment by frol** [comment]
@nearmax @damons @ilblackdragon Should we merge into staging first? This sounds ridiculous in some sense, as it is just a README file, but having a single process for all contributions is quite useful (also, this way we avoid possible merge conflicts if staging README gets changed for some reason that only makes sense once the code relevant to the README change in staging lands).

**Comment by lazaridiscom** [comment]
> Should we merge into staging first? 

Usual process is to merge to master, then go to stage then to release.

Where is your current process documented?

**Comment by frol** [comment]
@lazaridiscom Yes, you are right, that is the norm, but for historical reasons, we use our master as the "release" branch. (I hope we will change it.) May I ask you to rebase your commit on staging? (Simple changing the base to staging for this PR does not really work as we have some cherry-picks from staging, and if I just switch the base, those commits also get picked.)

**Comment by lazaridiscom** [comment]
> May I ask you to rebase your commit on staging?

No way. You've "killed my motivation by process", and I'm leaving everything to you now.

**Comment by lazaridiscom** [comment]
>  Yes, you are right, that is the norm, but for historical reasons, we use our master as the "release" branch.

You advertise "NEAR Protocol" as high-usability. Undocumented non-standard processes are really not the way to go.

You really need to fix this, yesterday.

**Comment by lazaridiscom** [comment]
@frol , you're overanalyzing things here https://github.com/nearprotocol/nearcore/pull/2153#issuecomment-588365300

just merge it (2 approvals there), nothing will explode.

**Comment by nearmax** [comment]
> @nearmax @damons @ilblackdragon Should we merge into staging first? This sounds ridiculous in some sense, as it is just a README file, but having a single process for all contributions is quite useful (also, this way we avoid possible merge conflicts if staging README gets changed for some reason that only makes sense once the code relevant to the README change in staging lands).

Everything should go into staging first as per process. Now that we have weekly cadence of releases (CC @damons ) there is only one week of delay before this change ends up in master.

**Comment by nearmax** [comment]
> You really need to fix this, yesterday.

You are right we should have documented our process. However, this is not good enough reason to deviate from it. @frol could you rebase it yourself and merge to staging?

**Comment by frol** [comment]
@nearmax Sure

**Comment by lazaridiscom** [comment]
I refuse to take part in this, in any way. A "Process" is non-existent, if undocumented. The relevant process is the one the medium you use dictates: github, the UI, which goes against master.

**Comment by lazaridiscom** [comment]
this is just ridiculous. Please realize it soon.

**Comment by frol** [comment]
@lazaridiscom We have just started fixing the process for external contributors. It is sad to see you go after putting your effort.

The reason for not working with master is that we land quite unstable features, which are massive, and we don't want to block each other with git conflicts, so we merge them early into staging and let master be stable for users. Once we fix the release process, we get back to using master as the main branch for forks and the rest.

I hope to see you around later once we fix our processes.

**Comment by lazaridiscom** [comment]
> after putting your effort

what effort? i used the github ui to post a fix. two min. work. The you all ruined my DX whilst going against standard-procedure and talking things to death.

@potatodepaulo , "Institutions and Processes", my email to you. Know when to ask for external help.

Have fun.

**Comment by lazaridiscom** [comment]
@frol , can you do me (and interested parties) a favor and file an issue where you describe the current problem "master vs stable"?

And possibly this here helps a bit: https://github.com/lazaridiscom/dapp-platform/issues/6

**Comment by frol** [comment]
@lazaridiscom Done: #2165

**Pull request closed without merging**
