### PR TITLE
Use LRU cache for storage

### PR DESCRIPTION
**Pull request by bowenwang1996**
Change caches used in storage from `HashMap` to LRU cache.

### CODE REVIEW

**Comment by nearmax** [comment]
That crate looks like someone's pet project. What are the other options? Could we compare them?

**Comment by bowenwang1996** [comment]
The other option is this https://github.com/maidsafe/lru_time_cache. The one we use now is small and easy to modify if we want.

**Comment by nearmax** [comment]
What about https://github.com/jaemk/cached and other repos that implement cache (including lru)?
What are pros and cons of these repos?

**Comment by nearmax** [comment]
What about https://github.com/stusmall/ttl_cache , https://docs.rs/chashmap/2.2.0/chashmap/  and other?

**Comment by bowenwang1996** [comment]
https://github.com/jaemk/cached has a nice trait for general cache, but does not have very good support for lru cache. Their `SizedCache` does not provide important functionalities like `contains` or `peek`. 
 https://github.com/stusmall/ttl_cache is a time-sensitive cache. I don't think we need time-related cache as time is not well-defined on blockchain.
 https://docs.rs/chashmap/2.2.0/chashmap/  seems to be a concurrent hashmap. I am not sure how that relates to lru cache.

**Comment by ilblackdragon** [comment]
This should fix #364

**Comment by nearmax** [comment]
It is unfortunate that we now perform double-lookup in `read_with_cache`

**Pull request merged**
