### PR TITLE
Promote EXPERIMENTAL_light_client_proof to non-experimental

### PR DESCRIPTION
**Pull request by nearmax**
For consistency with `next_light_client_block`

### CODE REVIEW

**Comment by nearmax** [comment]
@bowenwang1996 Currently, there is exactly one project using it, so I suggest we avoid the regular routine. E.g. `next_light_client_block` was introduced without `EXPERIMENTAL` in the first place.

**Comment by frol** [comment]
If we know that we are the only client, we can skip the step of having an alias. Sounds fine to me.

**Comment by evgenykuzyakov** [comment]
I believe it broke `nearlib-tests`
Screen Shot 2020-06-19 at 11 04 21 AM

**Comment by evgenykuzyakov** [comment]
I think next time we may want to keep the original `EXPERIMENTAL_light_client_proof` rpc endpoint as well, before we move `nearlib` to the new endpoint. And only then deprecate the `EXPERIMENTAL_light_client_proof`

**Comment by frol** [comment]
Why was not it caught by the CI as of this PR?

**Comment by evgenykuzyakov** [comment]
Maybe the test was pushed later: https://github.com/near/near-api-js/commit/350ff83c492e9e3e51477c550a8ccee2e5f39665

**Comment by evgenykuzyakov** [comment]
Also `nearlib` CI doesn't depend on master branch

**Comment by evgenykuzyakov** [comment]
Returning `EXPERIMENTAL_` back in https://github.com/nearprotocol/nearcore/pull/2874

**Pull request merged**
