### PR TITLE
Avoid CPU checks in runtime params estimator.

### PR DESCRIPTION
**Pull request by olonho**

### CODE REVIEW

**Comment by olonho** [comment]
> why do we do this? I think we should have this check if you run wasmer.

Idea is that we must do that on nodes, but some cases, such as param estimator where we know AVX paths are not triggered can be allowed. We could think of better approach, although.

**Comment by ailisp** [comment]
> param estimator should be running on the hardware that is similar to what we will be running live, so nodes without AVX should not be used, am I wrong?

param estimator is run under a qemu emulator, which also has avx, but qemu couldn't correctly indicate that. So to avoid this panic we have to skip that check in param estimator

**Comment by SkidanovAlex** [comment]
> So to avoid this panic we have to skip that check in param estimator

Would the approach in which the check is _disabled_ by a feature flag work for the param estimator?

**Comment by ailisp** [comment]
> Would the approach in which the check is disabled by a feature flag work for the param estimator?

@willemneal is testing on it as said in contract-runtime chat. Looks yes to be by read the code. What doesn't work is `is_x86_feature_detected!("avx")`, this check always return false in qemu.

**Comment by SkidanovAlex** [comment]
@ailisp I'm not sure I follow. What I'm suggesting is to add a feature flag that disables the check (as opposed to a feature flag which enables it, as in the PR right now)

**Comment by ailisp** [comment]
> @ailisp I'm not sure I follow. What I'm suggesting is to add a feature flag that disables the check (as opposed to a feature flag which enables it, as in the PR right now)

Ah got it

**Comment by olonho** [comment]
Fixed per Alex suggestions.

**Pull request merged**
