### PR TITLE
Exposed block height at which given query RPC was performed

### LINKED ISSUE #1778: Expose block height at which given query RPC was performed
Currently when a query RPC is performed, the result doesn't indicate at which height this state was.

The response should contains `height` attribute to indicate block height at which data was queried:
```
{
 query: "account/illia",
 data: "",
 result: { 
    amount: '21999999998322606201',
    code_hash: '11111111111111111111111111111111',
    locked: '0',
    storage_paid_at: 1757131,
    storage_usage: 506 
  },
  block_height: 123321
}
```

### PR DESCRIPTION
**Pull request by frol**
*Resolves #1778*

I have renamed `QueryResponse` to `QueryResponseKind` and added a wrapper `QueryResponse` struct which include `kind` + `block_height`.

I use `serde(flatten)` on the `kind` field to keep the API response backward compatible. From the RPC client point of view, a single `block_height` field has been added [a test case is added to ensure this] (cc @vgrichina):

```
$ http post http://127.0.0.1:3030/ jsonrpc=2.0 id=dontcare method=query 'params:=["account/test.near", ""]'

{
    "id": "dontcare",
    "jsonrpc": "2.0",
    "result": {
        "amount": "1000000000000000000000000000",
        "block_height": 83,
        "code_hash": "11111111111111111111111111111111",
        "locked": "50000000000000000000000000",
        "storage_paid_at": 0,
        "storage_usage": 182
    }
}
```

### CODE REVIEW

**Comment by frol** [comment]
I have hit into a rabbit hole. This PR works fine for all the queries but `AccessKey` and  `AccessKeyList`. `AccessKey` can be `None` and `AccessKeyList` is a vector, so they cannot be `serde(flatten)` (you cannot add a `block_index: 0` to a list of keys without wrapping those keys into a wrapping object). I have managed to workaround the `AccessKeyList` by wrapping the vector into an object with a `keys` field. I can do the same for `AccessKey`, but I don't understand why it can be None. In any case, adding `block_height` to those RPC calls will be a breaking API change!

@vgrichina @ilblackdragon Where do we use `query(access_key/...)` and `query(access_key/.../...)`? Should we keep the API stable no matter what and introduce separate endpoints for the breaking changes API?

**Comment by vgrichina** [comment]
> Where do we use `query(access_key/...)` and `query(access_key/.../...)`? 

in nearlib:
```
61:        this._accessKey = await this.connection.provider.query(`access_key/${this.accountId}/${publicKey.toString()}`, '');
190:        const response = await this.connection.provider.query(`access_key/${this.accountId}`, '');
```

> Should we keep the API stable no matter what and introduce separate endpoints for the breaking changes API?

I think we should start versioning API at some point. Like if you call from newer version of client – responses would have `block_index` / whatever new stuff, otherwise – no.

**Comment by nearmax** [comment]
Let me know when it is not WIP.

**Comment by frol** [comment]
FYI, I am going to introduce the breaking change (and fix the related code in App Layer projects) this time since the current API is not extendable and the response is misleading (e.g. you get `null` if anything goes wrong for AccessKey query, even if the account does not exist at all)

**Comment by frol** [comment]
This PR is ready to be merged once the new version of nearlib with the PR https://github.com/nearprotocol/nearlib/pull/132 is released.

**Comment by frol** [comment]
@nearmax ready to merge

**Comment by frol** [comment]
I could not reproduce [the issue "thread panicked while panicking. aborting"](https://gitlab.com/near-protocol/nearcore/-/jobs/372597616) locally, so after a few re-runs the tests pass O_o

Is this a known issue?

**Comment by bowenwang1996** [comment]
@frol https://github.com/nearprotocol/nearcore/issues/1426

**Comment by frol** [comment]
@bowenwang1996 @evgenykuzyakov @SkidanovAlex This PR is blocked on a review from code owners.

**Pull request merged**
