### PR TITLE
Fix contract initializer method

### PR DESCRIPTION
**Pull request by mikhailOK**
Remove the hack and fix the bug where the server hangs if smart contract
initalizer has an infinite loop.

### CODE REVIEW

**Comment by mikhailOK** [comment]
Fixes #542

**Comment by mikhailOK** [comment]
infinite_initializer is hand-written, to view in human-readable format run
wasm2wat infinite_initializer.wasm
```
(module
  (type (;0;) (func))
  (func (;0;) (type 0)
    loop  ;; label = @1
      br 0 (;@1;)
    end)
  (func (;1;) (type 0)
    block  ;; label = @1
    end)
  (export "hello" (func 1))
  (start 0))
```

**Comment by nearmax** [comment]
Please add these instructions somewhere in the repo including running wat2wasm and reference it from the unit tests.

**Comment by mikhailOK** [comment]
removed the file, moved it to the code

**Pull request merged**
