### PR TITLE
Fix authority keys, NAT network, sync & produce blocks integration works

### PR DESCRIPTION
**Pull request by ilblackdragon**
Start by launching consensus from the last block.

### CODE REVIEW

**Comment by nearmax** [comment]
So this code seems to be mostly #651. LGTM for that part.
I think this PR needs to have a more specific name, by I cannot come up with anything good.

**Comment by nearmax** [comment]
So the way it solved the problem with NAT is by allowing nodes to specify their `PeerInfo::addr` as None. Correct?

**Comment by nearmax** [comment]
Also, if I understood correctly you are saying this fixes this issue?
```
thread 'tokio-runtime-worker-4' panicked at 'Threshold is not found for given proposals: "Total stake 0 must be higher than the number of seats 2"', src/libcore/result.rs:1009:5
```

What is the fix, and why was it failing?

**Comment by ilblackdragon** [comment]
@nearmax

For network stuff: yeah, it's not really solving NAT, just allows nodes without public addresses to connect to the network. addr is option and if it's not present, `peer.rs` doesn't try to connect to it.

For authorities, the problem was that we didn't have `authority_mask` populated at all (so everybody got kicked out). The real fix will be in #645 but I just filled in with `true` for now for all authorities.

**Pull request merged**
