### PR TITLE
fix: tail should be updated when there are skips

### PR DESCRIPTION
**Pull request by bowenwang1996**
Currently in `clear_data`, if there is no blocks between tail and gc_stop_height, we would just run through the entire loop without updating tail, which leads to gc getting stuck. This PR fixes it by updating the tail even when there is no block at some height. Notice that this means that tail height doesn't necessarily imply the existence of a block at that height, but given that we only use it for gc purposes, I think it is fine.

Test plan
---------
`test_gc_tail_update` passes.

### CODE REVIEW

**Comment by Kouprin** [comment]
Is it true that we don't update tail after state sync which means tail is set improperly?
More precisely, tail is set to `genesis_height`, however is should be set to last existed block in the chain.

**Comment by Kouprin** [comment]
Discussed with @bowenwang1996 offline.
It's important to set a tail to the oldest existing block at the chain.
I suggest to do the following:
1. Update GC contract, add p. 5 to Prerequisites: tail is the height of the oldest existing block at the chain.
2. Update ChainStoreAccess `tail()` to NOT return `genesis_height` by default.
3. Don't run GC if `tail` is not set, print WARN and return.
4. Set tail manually:
4a. If start from genesis, set to `genesis_height`.
4b. If start from state sync, set to height of sync block.

**Comment by bowenwang1996** [comment]
@Kouprin I think what you suggested doesn't work directly. Let's say that you set your tail to genesis height when the node starts. Then, after the node has been running for four epochs it stopped or fall out of sync for some reason. When you restart your node, you do state sync, and after it is done, you set tail to sync hash, which means that you will never gc four blocks of data that you already have. If an adversary can trick you into doing state sync once in a while, you gc is basically completely disabled.

**Comment by Kouprin** [comment]
++ for merging this PR.
I see your point.
However, stopping at this point means that each new node will run `get_all_block_hashes_by_height()` method from `genesis_height` up to chain height, which mean millions of storage lookups for empty data. (This may lead to 100% CPU usage for a while with no useful data processing.)

**Comment by Kouprin** [comment]
> When you restart your node

There will be `TAIL` key in the database and no problem should appear, right?

**Comment by Kouprin** [comment]
> set tail to sync hash

once again: I set tail only if no tail in the database
if tail exists, we continue with existing one

**Comment by bowenwang1996** [comment]
> However, stopping at this point means that each new node will run get_all_block_hashes_by_height() method from genesis_height up to chain height, which mean millions of storage lookups for empty data. (This may lead to 100% CPU usage for a while with no useful data processing.)

I was definitely not suggesting stoping at this point. It is important that we fix this problem completely. 

> once again: I propose to set tail only if no tail in the database
if tail exists, we continue with existing one

Maybe I didn't understand what you proposed. But if we set the tail when a node starts, how is it that tail is not set when we do state sync? Then we would never set tail after state sync is done, which defeats the purpose.

**Comment by Kouprin** [comment]
> Maybe I didn't understand what you proposed.

If there is a tail in DB under `TAIL` key, use it. Otherwise:
1. If state sync happens, set DB `TAIL` key to sync block and update tail.
2. If GC started but tail is still not set, this means we started from the genesis, so set tail to `genesis_height`.

**Comment by bowenwang1996** [comment]
@Kouprin I have created an issue https://github.com/nearprotocol/nearcore/pull/2410 and let's discuss it there and address it in a separate PR. I think the solution you proposed still doesn't fully work because gc is not triggered at all for the first five epochs (meaning that tail will not be set while there are data) and if you do state sync then the old data will not be garbage collected.

**Comment by Kouprin** [comment]
> I have created an issue #2410

Please fix the link

**Comment by bowenwang1996** [comment]
@Kouprin link fixed. I would have fixed the issue right here if I fully agree with the solution, but I think there are some details that do not fully work.

**Comment by Kouprin** [comment]
> @Kouprin link fixed.

Thank you!

>  gc is not triggered at all for the first five epochs (meaning that tail will not be set while there are data) and if you do state sync then the old data will not be garbage collected

I can't understand this. Can we clearly divide the following situations:
a) we start from genesis;
b) we start with state sync.
If yes, the only thing is necessary is to set tail to: a) genesis_height; b) sync height.
If no, why? And how is it possible to receive any blocks at height of close to genesis if the whole chain is far enough to require state sync?

**Pull request merged**
