### PR TITLE
fix(test): abort in actix should treat as fail in tests

### PR DESCRIPTION
**Pull request by ailisp**
In #2871 @Kouprin found tests are failed but marks at pass in nightly

Test Plan
---------
Add panic! at same place of 
```
thread 'tests::test_catchup_random_single_part_sync_send_15' panicked at 'assertion failed: block.header().height() <= 32', chain/client/tests/catching_up.rs:508:37
```
as in
http://nightly.neartest.com/run/master_9bdc06527451f54d2fbdbd9ea6e8904556513928_20200622_144553/expensive/expensive_near-client_catching_up_tests__test_catchup_random_single_part_sync_send_15/stderr
and observe test fails with exit code 101 (And backtrace is still readable)

### CODE REVIEW

**Comment by ailisp** [comment]
> How is this different from replacing this function init_stop_on_panic with debug_assert!(false)?

We still want init_stop_on_panic for prod build, so it print panic in actix actor and continue.

**Comment by mikhailOK** [comment]
This will always give thread panicked while panicking I think. 

Have we always swallowed panics from that test, or it's related to a recent change like #2869? Or is it an issue with how nightly runs tests?

**Comment by SkidanovAlex** [comment]
@mikhailOK since we updated actix to 1.1.1 ~2 months ago, some tests started being marked as passed even if they fail. Seems like this hook doesn't always work anymore. Note that it is sporadic (sometimes the very same tests failing on the very same assert are marked as failed), and is somehow specific (or is more likely) to the nightly runners, on my local machine I can't reproduce it.

I don't think this change solves it, because the thread in which this `debug_assert` is executed is already panicing. If panicing in that thread was enough, the test would already fail.

Bo, can you confirm that locally:
1. Without your change you can actually reproduce the test passing but printing the stack trace
2. With your change you do not receive "panicked while panicking"? If you do receive it, the test will not be runnable from CLion, and being able to run tests from CLion is crtitical.

I suggest we implement the fix I proposed (to check the stderr for the presence of a stacktrace and mark tests in nightly as failed if there's one) now, so that nightly becomes usable immediately, and then figure out how to fix it properly separately.

**Comment by ailisp** [comment]
> This will always give thread panicked while panicking I think.

You're right

> Have we always swallowed panics from that test, or it's related to a recent change like #2869? Or is it an issue with how nightly runs tests?

I guess only happens threads are cleaned up earlier and text exit(0) before actix panic is handled

> Without your change you can actually reproduce the test passing but printing the stack trace

Seems i cannot reproduce Kouprin's "test failed but exit(0)" in any way, so cannot tell if this fix or not, will check stacktrace in nightly instead

**Pull request closed without merging**
