### PR TITLE
Neard version bump 1.1.0

### PR DESCRIPTION
**Pull request by chefsale**
Version bump for the new release: https://github.com/nearprotocol/nearcore/tree/v1.1.0
based from beta release: https://github.com/nearprotocol/nearcore/releases/tag/beta-2020-06-03 and commit: https://github.com/nearprotocol/nearcore/commit/a4f57f91ad020e52947181d20b48c7c7b6a51f5f

### CODE REVIEW

**Comment by frol** [comment]
I’m confused with the versioning and betanet relation. That code is much older than the master branch

**Comment by chefsale** [comment]
Hmm, not sure what you mean? So we decided that we will soaked beta release into a release after a week. Now we catch up (rebase) the beta branch, but that should change in the future once we delete the stable and beta branch and just use tagging on master.

**Comment by chefsale** [comment]
This was the procedure we decided to go with:
- Alpha - latest master build running on devnet daily
- Beta - 1 weekly builds running on betanet
    - everything goes into master linearly, except critical security patches and bug fixes
- Release Candidate
    - 1 weeks of stabilization on testnet
    - we only cherry-pick critical security patches and bug fixes included in previous releasesinto the rc branch
    - we revert newly introduced bugs from the last release instead of forward fixing new issues
- Stable - we create a stable release and repeat

**Comment by nearmax** [comment]
Could we have a changelog both in CHANGELOG.md file and in the github release section, similarly to how we did it here: https://github.com/near/near-sdk-rs/releases/tag/v0.11.0 ?

**Comment by frol** [comment]
> we will do stable release based on the soaked beta after a week.

With this PR you are going to mark the latest master code as 1.1.0 instead of the "soaked beta" code.

> Now we catch up (rebase) the beta branch, but that should change in the future once we delete the stable and beta branch and just use tagging on master.

It is unclear how tagging on a single branch will work for hotfixes. Can you elaborate on that or point me to the relevant discussion?

**Comment by chefsale** [comment]
> With this PR you are going to mark the latest master code as 1.1.0 instead of the "soaked beta" code.

Yes, everything in master is going to be 1.1.0 until the new version bump.

> It is unclear how tagging on a single branch will work for hotfixes. Can you elaborate on that or point me to the relevant discussion?
For hot fixes you will push them into the v1.1.0, etc branch and re-merge it into master.

**Pull request merged**
