### PR TITLE
Revert "feat: Disable creation of short top-level account ids"

### PR DESCRIPTION
**Pull request by ilblackdragon**
Reverts nearprotocol/nearcore#2355

We haven't finalized the design and App Layer implementation.

### CODE REVIEW

**Comment by ilblackdragon** [comment]
@evgenykuzyakov 
Here are all the missing pieces that needs to be done before merge:
 - [ ] nightly tests are passing
 - [ ] nearlib errors are updated & new nearlib & near-shell are released
 - [ ] DevX accounts for this @potatodepaulo :
   - [ ] for `localnet` works correctly, among other things our examples have TLA in the instructions
   - [ ] devnet / betanet / testnet  same
 - [ ] UserX accounts for this @kcole16 :
   - [ ] Wallet creates accounts with .testnet / .betanet / .devnet prefixes

**Comment by evgenykuzyakov** [comment]
Instead let's just disable config. I'll make a PR

**Comment by evgenykuzyakov** [comment]
Created a PR to disable registrar: https://github.com/nearprotocol/nearcore/pull/2362
This will allow testing of app-layer with local config.

While if we revert the original PR, then app layer will not be able to test changes, so it will take much longer.

**Comment by ilblackdragon** [comment]
Closing with fix #2362 instead

**Pull request closed without merging**
