### PR TITLE
Update wasmer to 13.1

### PR DESCRIPTION
**Pull request by fckt**

### CODE REVIEW

**Comment by mikhailOK** [comment]
`default-backend-singlepass` is still there, should be ok

**Comment by fckt** [comment]
@nearmax  There is no single-pass-backend feature in `wasmer-runtime-core` anymore.

**Comment by nearmax** [comment]
What is `deterministic-execution` feature?

**Comment by fckt** [comment]
> What is deterministic-execution feature?

It enables a `wasmparser`'s "deterministic" feature which forbid floats. I disabled this feature.

https://github.com/bytecodealliance/wasmparser/blob/9fb1b00cad7e47ffd774c75443728c0cd0afbb41/src/operators_validator.rs#L636

**Comment by nearmax** [comment]
Can you make sure it still executes the singlepass compiler and not the LLVM one?

**Comment by fckt** [comment]
>> Can you make sure it still executes the singlepass compiler and not the LLVM one?

We are using the following function to compile Wasm:
https://github.com/wasmerio/wasmer/blob/master/lib/runtime/src/lib.rs#L243
It uses the `default_compiler` function as input. The `default-backend-singlepass` changes the output of the `default_compiler` function to `wasmer_singlepass_backend::SinglePassCompiler`.

**Comment by fckt** [comment]
@nearmax merge?

**Pull request merged**
