### PR TITLE
add links to Issues/Milestones

### PR DESCRIPTION
**Pull request by lazaridiscom**

### CODE REVIEW

**Comment by lazaridiscom** [comment]
> Merging #2144 into master will increase coverage by 0.08%.

well, well...

**Comment by bowenwang1996** [comment]
@damons @ilblackdragon our milestones are quite outdated. Should we make an effort to fix it?

**Comment by lazaridiscom** [comment]
> our milestones are quite outdated

they look quite actual (nearly all issues are assigned to the 2 milestones)

**Comment by bowenwang1996** [comment]
Oh I see. Looks like we already updated it

**Comment by ailisp** [comment]
> > Merging #2144 into master will increase coverage by 0.08%.
> 
> well, well...

Some integration test is not very deterministic

**Comment by lazaridiscom** [comment]
> 
> 
> > > Merging #2144 into master will increase coverage by 0.08%.
> > 
> > 
> > well, well...
> 
> Some integration test is not very deterministic

I filed a complaint @ GitHub, asking to provide me a means to block this highly annoying/intrusive bot of Codecov. No luck till now. I mean look at the size off its totally off-topic comment...

**Comment by bowenwang1996** [comment]
@lazaridiscom we have disabled codecov in staging and it will be disabled in master when we merge staging into master.

**Comment by lazaridiscom** [comment]
Sounds good! (#2002)

**Pull request merged**
