### PR TITLE
nearcore build in our official Docker image did not sent telemetry data

### LINKED ISSUE #1840: Nearcore running in Docker container does not sent telemetry data
A few people reported in Discord that they don't see their nodes in Explorer. After some investigation, I realized that the issue is the Docker environment (the locally built binary and Docker image from the same commit result in that nearcore running in Docker container does not report telemetry data while running it on the host system works just fine).

I will investigate it further.

/cc @bowenwang1996 @ilblackdragon @nearmax

### PR DESCRIPTION
**Pull request by frol**
*Resolves #1840*

Should we cherry-pick this to master?

### CODE REVIEW

**Comment by ilblackdragon** [comment]
🤦‍♂

**Comment by frol** [comment]
What is wrong with CI?

**Comment by ailisp** [comment]
@frol imo gitlab bug. it's mirrored to https://gitlab.com/near-protocol/nearcore/tree/bugfix/1840-no-telemetry-data-from-docker-image
and gitlab is configured to "Run pipeline on every branch when there's a commit to new branch" and it isn't triggered. Let me manually trigger it.

**Comment by frol** [comment]
The CI failure is unrelated to the change. Should we force-merge it or restart CI?

**Comment by ailisp** [comment]
I think it’s okay to force merge. Some ci like google cloud build allow
some file changes like read me to be ignored. Let me see if gitlab support
this too. Even if it’s not supported we are moving to the py script to
test, the skip logic can be add there

**Comment by frol** [comment]
Well, I don't seem to have enough permissions to force-push it :(

Can you do this?

**Pull request merged**
