### PR TITLE
fix(view_client): broadcast_tx_commit should wait until all receipts …

### PR DESCRIPTION
**Pull request by bowenwang1996**
…finish

Currently `broadcast_tx_commit` would return if one receipt is successfully executed. However, in the case where the receipt generates some further receipts, it will not wait until those receipts finish, which caused some pain for applayer. See https://github.com/nearprotocol/near-wallet/pull/440#discussion_r390055497.

Test plan
--------
* Add pytest `transaction_status.py` to check that when a receipt creates further receipts `broadcast_tx_commit` wait until all of them finish before returning.

### CODE REVIEW

**Comment by evgenykuzyakov** [comment]
It's an issue with the implementation of link drop. It's not an issue with how transactions work.

**Comment by bowenwang1996** [comment]
> It will delay result for every single function call because we'll have to wait on the refund receipts. This will introduce one extra block of delay for every single function call transaction.

I think it doesn't wait for refund receipt as it is not generated by any existing transaction or receipts.

**Comment by evgenykuzyakov** [comment]
Check out the following on explorer: https://explorer.nearprotocol.com/transactions/BBPMYRuxgTCXE28V6dVDu5YsSNdbPU99m81ytgYwaryH

```json
Transaction chad:BBPMYRuxgTCXE28V6dVDu5YsSNdbPU99m81ytgYwaryH
{
  receipts_outcome: [
    {
      block_hash: 'EeG9kukpF6JtYYLvmEFHezwEctEJ64Q9uuxDKp5yKVFJ',
      id: '6P3ZCm7UcxSRKiRuKQJgvXQ2uu4FzF4t9zYQaYHmqqPS',
      outcome: {
        gas_burnt: 2485541425048,
        logs: [],
        receipt_ids: [ 'nAbgSkWhi4AkaDDCwJLk34DQnD5H39JsJyo4L7wzjyV' ],
        status: { SuccessValue: '' }
      },
      proof: []
    },
    {
      block_hash: 'Hb8x82prtKHi2K1TJoZT3P3HxzpjZUSfeWV1zG63bwY1',
      id: 'nAbgSkWhi4AkaDDCwJLk34DQnD5H39JsJyo4L7wzjyV',
      outcome: {
        gas_burnt: 0,
        logs: [],
        receipt_ids: [],
        status: { SuccessValue: '' }
      },
      proof: []
    }
  ],
  status: { SuccessValue: '' },
  transaction: {
    actions: [
      {
        FunctionCall: {
          args: 'eyJ0ZXh0Ijoid2hvYSBob3cgY29vbCBpcyB0aGlzIn0=',
          deposit: '0',
          gas: 2000000000000,
          method_name: 'addMessage'
        }
      }
    ],
    hash: 'BBPMYRuxgTCXE28V6dVDu5YsSNdbPU99m81ytgYwaryH',
    nonce: 1,
    public_key: 'ed25519:AcpvPtftmi4ivWY3vVfwLAKyJwjVUe7ENPnS3fZ6MbF2',
    receiver_id: 'dev-1582817300252',
    signature: 'ed25519:3U1PgWcykhXpqYhLFoihExuDigpkLBQMvtYyKnTEvojrSiXQ2a7d8CNunc8rq9YwtLGMdp5rfASSUqLbjijnaLuU',
    signer_id: 'chad'
  },
  transaction_outcome: {
    block_hash: 'E1N8wnzEvop53VMMc2NNmNiNgCGgDgcHKXdrfY7eZx3X',
    id: 'BBPMYRuxgTCXE28V6dVDu5YsSNdbPU99m81ytgYwaryH',
    outcome: {
      gas_burnt: 2291590908026,
      logs: [],
      receipt_ids: [ '6P3ZCm7UcxSRKiRuKQJgvXQ2uu4FzF4t9zYQaYHmqqPS' ],
      status: {
        SuccessReceiptId: '6P3ZCm7UcxSRKiRuKQJgvXQ2uu4FzF4t9zYQaYHmqqPS'
      }
    },
    proof: []
  }
}
```

The first receipt is function call execution on the `receiver`:
```json
{
      block_hash: 'EeG9kukpF6JtYYLvmEFHezwEctEJ64Q9uuxDKp5yKVFJ',
      id: '6P3ZCm7UcxSRKiRuKQJgvXQ2uu4FzF4t9zYQaYHmqqPS',
      outcome: {
        gas_burnt: 2485541425048,
        logs: [],
        receipt_ids: [ 'nAbgSkWhi4AkaDDCwJLk34DQnD5H39JsJyo4L7wzjyV' ],
        status: { SuccessValue: '' }
      }
```
It has `status: { SuccessValue: '' }` which means the transaction is done, but it also has non-empty `receipt_ids`. This receipt is a refund

**Comment by bowenwang1996** [comment]
Okay I see. Do you think an additional 1s delay is bad? Currently there is no easy way to tell if a transaction has truly finished (all receipts done) and maybe that is something that people want. @kcole16

**Comment by evgenykuzyakov** [comment]
We should add an API to query receipt status and individual receipts.

Linkdrop contract can be updated to wait for the creation of the new account, as I mentioned in the linked comment above

**Comment by bowenwang1996** [comment]
Sounds good

**Pull request closed without merging**
