### PR TITLE
Merging master to staging

### PR DESCRIPTION
**Pull request by ilblackdragon**
Bringing changes post 0.3.0 release & merging trees back to not have future conflicts.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
Some test is failing

**Comment by ailisp** [comment]
Occasionally we have merge from staging to master and merge master to
staging. Would it be a good idea to periodically abandon staging, create a
new staging from master.

**Comment by ilblackdragon** [comment]
@ailisp you are right, next time we should after merging staging into master, reset staging to that commit.
This time it just has been 3 branch juggle.

**Comment by ailisp** [comment]
@ilblackdragon Did you do something special when merge master to staging? After I did this PR and try create PR from master to staging again: https://github.com/nearprotocol/nearcore/compare/staging...master?expand=1
it still shows all commits since Sep 11 (Your last sync time), even if all these updates are already in staging. (Example: METRICS.md)

**Comment by ailisp** [comment]
Ah i think i got it. I shouldn't squash and merge :(

**Pull request merged**
