### PR TITLE
Fix(test): fix catch up test

### LINKED ISSUE #2145: Catchup tests fail
- [x] test_catchup_random_single_part_* fixed in https://github.com/nearprotocol/nearcore/pull/2146
- [x] test_catchup_receipts_sync_distant_epoch fail (related to GC)

### PR DESCRIPTION
**Pull request by bowenwang1996**
Fix catchup tests. Fixes #2145 

Test plan
--------
Test that catchup tests work after this fix.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
@Kouprin it passes for me. What error did you observe?

**Comment by Kouprin** [comment]
> @Kouprin it passes for me. What error did you observe?

I reran on branch `fix-catchup-test`.

```
thread 'tests::test_catchup_receipts_sync_distant_epoch' panicked at 'assertion failed: `(left != right)`
  left: `1`,
 right: `1`', chain/client/tests/catching_up.rs:229:37
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/vsts/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:76
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:60
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:64
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:196
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
             at /rustc/032a53a06ce293571e51bbe621a5c480e8a28e95/src/liballoc/boxed.rs:924
  11: near_primitives::test_utils::init_stop_on_panic::{{closure}}::{{closure}}
             at core/primitives/src/test_utils.rs:76
  12: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
  13: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:380
  14: std::thread::local::fast::Key<T>::try_initialize
  15: catching_up::tests::test_catchup_receipts_sync_common::{{closure}}::{{closure}}
             at chain/client/tests/catching_up.rs:229
```

Same in nightly.

**Comment by bowenwang1996** [comment]
Does it fail deterministically? I somehow cannot reproduce

**Comment by bowenwang1996** [comment]
@Kouprin Thanks. Are you on mac or linux?

**Comment by Kouprin** [comment]
> @Kouprin Thanks. Are you on mac or linux?

MacOS Catalina.

**Comment by bowenwang1996** [comment]
Strange. I am on MacOS mojave. I ran the test at least four times but it always passed for me.

**Pull request merged**
