### PR TITLE
Show help instead of panic with no subcommand

### PR DESCRIPTION
**Pull request by ailisp**
A small user experience improvement

### CODE REVIEW

**Comment by ilblackdragon** [comment]
@ailisp you can merge this to master

**Comment by ilblackdragon** [comment]
Also should we instead of `(_, _) => unreachable!(),` at the end of the match also show help?

**Comment by ailisp** [comment]
> Also should we instead of (_, _) => unreachable!(), at the end of the match also show help?

I'm thinking this way at the beginning too, but I had trouble finding a function to show help in clap crate. So eventually I find and use this flag.

**Comment by ailisp** [comment]
> @ailisp you can merge this to master
blocked by "need one approving review", can you approve it? Thanks!

**Pull request merged**
