### PR TITLE
Release 0.4.12

### PR DESCRIPTION
**Pull request by bowenwang1996**
Release notes:
* Fix rocks-db configuration.
* Add ttl to routed messages.
* Fix stake return bug when someone is slashed due to double signing blocks.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
@nearmax it does. Why do you think the fees are not turned on?

**Comment by nearmax** [comment]
> @nearmax it does. Why do you think the fees are not turned on?

In `v0.4.12` they are turned on, but in `staging` branch they are not, you can see they all have ones instead of large values https://www.dropbox.com/s/63vhkw38yt1drkb/Screenshot%202020-01-09%2011.30.33.png?dl=0

**Comment by bowenwang1996** [comment]
Yes because I didn't merge master into staging yet. That seems to be a separate issue not related to this PR.

**Comment by nearmax** [comment]
> Yes because I didn't merge master into staging yet. That seems to be a separate issue not related to this PR.

The issue is that the way we are making releases is incorrect. See release 0.4.11 that was done 20+ days ago, that release already included PR that enabled fees (https://github.com/nearprotocol/nearcore/pull/1827) but somehow after that release we still have fees turned off on the staging branch. Why haven't we updated config in `staging` branch 20+ days ago?

Because of that, we cannot run the node from the `staging` code today. If someone checks out `staging` branch and tries to run the node from that code, e.g. using `./scripts/start_unittest.py --local` they will run node with invalid config which will result in either node crashing or running incorrectly.

**Comment by ailisp** [comment]
Separate question, do we want to delete 0.4.12 from dockerhub, revert latest to last version?

**Pull request merged**
