### PR TITLE
Always build pairing with optimizations

### PR DESCRIPTION
**Pull request by mikhailOK**
speed up nightshade in debug

### CODE REVIEW

**Comment by nearmax** [comment]
@azban What is your take on using nightly rust? We need its feature to always build crypto library as release because it is too slow in debug.

**Comment by azban** [comment]
i'm fine with nightly, especially before mainnet

**Comment by azban** [comment]
i have a change [here](https://github.com/nearprotocol/nearcore/compare/pairing_always_o3-gitlab-test) that uses nightly rust.. it disables clippy for the time being, because it's not able to be built with the latest nightly rust. i asked in the rust/clippy discord [channel](https://discord.gg/pGmNN5) and am waiting to hear back

**Comment by nearmax** [comment]
@azban Cool, do you want to make a PR out of it, or there is something else that we need to do first?

**Pull request merged**
