### PR TITLE
fix verbose

### LINKED ISSUE #1729: `--verbose` argument breaks start_* scripts
Starting a localnet with `--nodocker --verbose` arguments I get the following "error":

```
$ ./scripts/start_localnet.py --nodocker --verbose
Using existing node configuration from /home/frol/.near/ for test-chain-uQpwW
Stake for user 'test.near' with 'ed25519:FyFVyYV6o9pPfp5V1i8Gb69L6M9o8Ud8VYeAuf8T2ecr'
Starting NEAR client...
Autoupdate is not supported at the moment for runs outside of docker
error: Found argument '--telemetry-url' which wasn't expected, or isn't valid in this context

USAGE:
    near --home <home> --verbose <verbose>

For more information try --help
```

Dropping the `--verbose` argument it gets working just fine.

P.S. I am trying my best to ping the relevant people for this issue (there are no code-owners for ./scripts and ./near folders): @ailisp @bowenwang1996 @nearmax

### PR DESCRIPTION
**Pull request by ailisp**
Fix #1729

### CODE REVIEW

**Comment by ailisp** [comment]
[a].append([b, c]) becomes [a, [b, c]]

**Comment by bowenwang1996** [comment]
Sorry I meant extend.

**Comment by frol** [comment]
Hmmm, this seems to be a bug in arguments passing on the near binary then, this workaround is brutal. Can we fix the arguments parsing instead?

**Comment by ailisp** [comment]
@bowenwang1996 I guess i was too lazy to modify existing line :joy:
@frol it's not a bug in nearcore, nearcore accept `--verbose <str>`, where str can be either empty or takes list of modules to have DEBUG log level. see near/main.rs. Due to command line limitation it cannot be `--verbose <Option<str>>` a nice work around would be `--verbose`: a flag for verbose all. `--verbose-module <str>` take modules to verbose. But this small improvement doesn't add actual functionality, so i think doesn't worth a change right now.

**Comment by ailisp** [comment]
Yeah, this kind of verbose looks weird to me too.

**Pull request merged**
