### PR TITLE
Remove nearshell dep

### PR DESCRIPTION
**Pull request by willemneal**
Now asc is called directly instead of depending on near-shell.

### CODE REVIEW

**Comment by willemneal** [comment]
Also the according to github the generated binary is 37% smaller with the new bindings code!

**Comment by ilblackdragon** [comment]
Can you rebase/merge to latest staging - I think you had a version where staging was failing test_cargo tests.

**Comment by willemneal** [comment]
I updated to the new compiler for the integration tests, but it seems to fail before it gets to it.

**Comment by bowenwang1996** [comment]
Looks like this change somehow made our runtime slower and that's why the some tests failed.

**Comment by willemneal** [comment]
Well I have some ideas of how to make the decoding faster, but went with correct implementation first.  Can we extend the tests just for now or is it a deal breaker?

**Comment by ilblackdragon** [comment]
As this is very outdated, going to close. Can be re-created if it's still needed.

**Pull request closed without merging**
