### PR TITLE
fix(state_sync_massive): Epoch length was too short

### LINKED ISSUE #3130: state_sync_massive.py fails with timeout
http://52.149.162.182:3000/#/test/7613

### PR DESCRIPTION
**Pull request by mfornet**
Epoch length was too short (20) and observer when tried
to sync, used old epoch, but right now, trying to sync from
any epoch other than current epoch or previous epoch is considered
malicious behavior.

Fixes #3130

Test plan
======

state_sync_massive.py passes in nightly

### CODE REVIEW

**Comment by mfornet** [comment]
Waiting for nightly test to pass: 
http://nayduck.eastus.cloudapp.azure.com:3000/run/148#/run/148

**Comment by bowenwang1996** [comment]
@mfornet looks like it failed

**Comment by SkidanovAlex** [comment]
@mfornet you also do not trigger state sync right now I think, I believe it needs to be at least two epochs in today for the observer to actually trigger the state sync (so you probably need to change 101 and 201 to 201 and 301 correspondingly).
I would assert using the log tracker that the state sync was indeed triggered, the same way that we do in `state_sync.py`

**Comment by mfornet** [comment]
This test is performing really poorly on nayduck while passing locally. I've need to adjust few times the size of the epoch, since the protocol relies in the assumption that the node will be able to sync in less than one epoch.

[Node0](https://nayduckdiag.blob.core.windows.net/logs/33015_test0)
[Node1](https://nayduckdiag.blob.core.windows.net/logs/33015_test1)

Most notably on nayduck, nodes produced 115 blocks in 20 minutes which is a sign that something is going really wrong. I see in logs from node0 that there are a lot of messages being dropped (which is very weird in this setup with only 2 nodes). However this should not be an issue anymore after #3088 lands. 

What puzzles me is that it works every single time locally while failing on nayduck. Probably the reason is a combination of (low performant machine + small epoch length + large state). Notice that in the run above, the node2 didn't even started, so the issue is not with the new node syncing. 

@SkidanovAlex @bowenwang1996 are you aware of any protocol mechanism that heavily depends on the epoch length being large enough, otherwise defaulting to significant slowdown?

**Comment by bowenwang1996** [comment]
@mfornet can you disable storage check in the test? Looks like it is causing quite a bit of slowdown while the node is running

**Comment by mfornet** [comment]
> @mfornet can you disable storage check in the test? Looks like it is causing quite a bit of slowdown while the node is running

It passed nayduck after removing `storage_check` 💯 
http://nayduck.eastus.cloudapp.azure.com:3000/#/test/33017

**Comment by bowenwang1996** [comment]
> It passed nayduck after removing storage_check 💯

Epic 🚀

**Comment by SkidanovAlex** [comment]
Can we add the assert that the node actually state_synced (not block synced)? Like at the end of `state_sync.py`:

```
assert tracker.check("transition to State Sync")
```

**Comment by mfornet** [comment]
> Can we add the assert that the node actually state_synced (not block synced)? Like at the end of `state_sync.py`:
> 
> ```
> assert tracker.check("transition to State Sync")
> ```

http://nayduck.eastus.cloudapp.azure.com:3000/#/run/401

**Review by SkidanovAlex — APPROVED** [review]

**Pull request merged**
