### PR TITLE
sync from master ci

### PR DESCRIPTION
**Pull request by ailisp**

### CODE REVIEW

**Comment by ilblackdragon** [comment]
Weird, timed out in track_shards test here.

**Comment by bowenwang1996** [comment]
I also have that problem locally. Should increase timeout to 10s

**Comment by ailisp** [comment]
@bowenwang1996 good point

**Comment by ailisp** [comment]
wait it's already 10s:
```
BBBB Slept 10100; max_wait_ms 10000
```

**Comment by ailisp** [comment]
I'm thinking of run ci on a gitlab shell runner, instead of docker runner, which may give a similar stable and less timeout issue. What do you think? @bowenwang1996 @ilblackdragon

**Comment by ailisp** [comment]
Close as new gitlab-ci.yml for staging is in #1451

**Pull request closed without merging**
