### PR TITLE
fix(rpc): add timestamp_nanosec to keep backward compatibility

### PR DESCRIPTION
**Pull request by bowenwang1996**
Add `timestamp_nanosec` to keep backward compatibility on rpc side that was broken by #2912. Also fixes light client pytests that were broken because of the change.

### CODE REVIEW

**Comment by bowenwang1996** [comment]
I think this is also used by explorer @frol.

**Comment by nearmax** [comment]
When it comes to the protocol changes, we should prioritize cleanliness of the very core structures like light client header over not breaking the API.

**Comment by nearmax** [comment]
@bowenwang1996 do I understand correctly that this change does not alter what is hashed, merkle-lized, and signed by the validators?

**Comment by bowenwang1996** [comment]
@nearmax right, it doesn't change anything related to the protocol.

**Comment by bowenwang1996** [comment]
@nearmax @frol can we make a decision on this? I am fine with either option.

**Comment by frol** [comment]
I think we should have an appropriate type (string) and I prefer to have a self-descriptive field name, also, it would be great to have a non-breaking change, so keeping the old name with the old type for a while makes the most sense to me given this is only RPC-facing change

**Comment by SkidanovAlex** [comment]
> right, it doesn't change anything related to the protocol.

I thought `LightClientBlockView` is what the bridge receives, and the `BlockHeaderInnerLiteView` inside of it is what we deborshify and SHA256 to get the hash? If that's the case, making `BlockHeaderInnerLiteView` to differ from `BlockHeaderInnerLite` will break the bridge.

**Comment by nearmax** [comment]
> > right, it doesn't change anything related to the protocol.
> 
> I thought `LightClientBlockView` is what the bridge receives, and the `BlockHeaderInnerLiteView` inside of it is what we deborshify and SHA256 to get the hash? If that's the case, making `BlockHeaderInnerLiteView` to differ from `BlockHeaderInnerLite` will break the bridge.

Since it is not part of the hash, the relay will read JSON light client header, but will ignore the old timestamp when constructing borsh object that it will pass to the bridge.

**Comment by SkidanovAlex** [comment]
> when constructing borsh object that it will pass to the bridge.

When construction borsh object of what type?

**Comment by nearmax** [comment]
> > when constructing borsh object that it will pass to the bridge.
> 
> When construction borsh object of what type?

Of the old type without this field https://github.com/near/rainbow-bridge/blob/master/environment/lib/near2eth-relay.js#L32. I mean, this change is not breaking the hypothetical currently running bridge, but we still need to update it to update the bridge code to be more consistent with the nearcore structures.

**Comment by SkidanovAlex** [comment]
@nearmax as of after this change `timestamp` is no longer returned as JSON string, it's returned again as JSON 53-bit integer, so I think it will break the line you are quoting (it will have to be updated to be `timestamp_nanosec`) if the timestamp of a block loses precision when stored as 53-bit integer?

**Comment by bowenwang1996** [comment]
@SkidanovAlex yes light client code has to change (should be straightforward though). @frol I suggest that since light client has already updated to use `timestamp` as a string, we do not do this change to keep backward compatibility this time because otherwise we are breaking light client.

**Comment by frol** [comment]
@bowenwang1996 we broke all the clients out there, and while this change is only in devnet, I suggest we unbreak it by having timestamp as a JS-number as it used to be, and update light client once again.

**Comment by SkidanovAlex** [comment]
Frol's reasoning sounds good to me.
@nearmax unblock if you are OK to upgrade the bridge to use `timestamp_nanosec`

**Comment by nearmax** [comment]
> Frol's reasoning sounds good to me.
> @nearmax unblock if you are OK to upgrade the bridge to use `timestamp_nanosec`

Let me pin specific nearcore version in rainbow repo so that we don't crash security audit review. Currently rainbow tests pull the most recent master.

**Pull request merged**
